name: Deploy 11ty octo_site

on:
  push:
    branches:
      - main  # Utilise 'main' au lieu de 'master'

jobs:
  build-deploy:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [20.x]  # Met à jour pour utiliser la version 20.x

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

	  - run: npm install 
      - name: Deploy to Github Pages
        run: |
          npm ci
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site  # Assure-toi que cela correspond au répertoire de sortie d'Eleventy
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilise ton token d'accès personnel

